version: "3"
services:
  gateway:
    container_name: nginx-gateway
    build: .
    ports:
      - "80:80"
    volumes:
        - ~/html:/usr/share/nginx/html
  rabbitmq:
    image: "rabbitmq:3.13-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"