name: Deploy with docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: datasaude
    steps:
      - name: building app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 177.93.131.216
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 5m
          script: |
            echo "Criando diretório"
            mkdir -p ~/app
            cd ~/app/
            echo "Clone repositório"
            [ -d nginx-gateway ] && rm -rf nginx-gateway
            git clone https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/cbeloni/nginx-gateway.git           
            echo "Buildando projeto"
            cd ~/app/nginx-gateway
            docker-compose up -d --no-deps --build